### PR TITLE
Build: cleanup and swap Markdownlint to Node version

### PR DESCRIPTION
**Pull request by nschonni**
https://github.com/DavidAnson/markdownlint seems to be a bit better maintained and with more IDE integrations now. It also runs on Node instead of Ruby, which tends to be easier to setup on GoC machines.
It also allows inline HTML disabling of rules, so we can opt out of odd things like the multiple H1s in the bilingual documents.

Outstanding fixes that I didn't tackle here:
- MD013 Line length, since that would need alot of document reflow
- MD024 Duplicate headers, since there are H3 things like `Checklist` that are currently reused in the same docs
- MD036 Emphasis for headers, is flagging all the `**TODO**` that will likely go away as the document evolves

### CODE REVIEW

**Comment by pjackson28** [comment]
@nschonni I looked through each of the changes and they look good to me. Does the build come back with no failures? Is the markdownlint dependency pretty stable/future-safe (so low risk of the build breaking in the future)?

**Comment by nschonni** [comment]
> Does the build come back with no failures?

Yes, I'm not sure why Travis didn't kick in here. I was able to manually trigger a build on their sit from this repo, so I thought the hook was good. Maybe one of the owners in this org needs to turn it on fully /cc @MaryBethBaker @smellems 



> Is the markdownlint dependency pretty stable/future-safe (so low risk of the build breaking in the future)?

Can't say for sure, but it seems to be used by other build tool projects, so that's probably a good sign https://github.com/DavidAnson/markdownlint#examples
I also left in the package lock, so we shouldn't see breaking subproject stuff, unless we hit a `left-pad`/unpublish situation again.

**Comment by pjackson28** [comment]
@MaryBethBaker @smellems I don't have access to the "Settings" for this repository likely because I am listed as just a Member rather than an Owner for canada-ca. Can Thomas and I be elevated to Owner status so we can control the settings for this repository, including the necessary settings for Travis?

**Comment by pjackson28** [comment]
@nschonni I just flicked on the switch on Travis for this repo.

**Comment by pjackson28** [comment]
@nschonni Would you prefer I do a "Squash and merge" to combine all the commits into one or to keep them separate when merging?

**Comment by nschonni** [comment]
No preference, they are separate, but if you want to squash them they are all related anyway

**Pull request merged**
