### PR TITLE
build: add Travis-CI config

### PR DESCRIPTION
**Pull request by nschonni**
Still a bunch of build failures, just throwing it over so it can be iterated on.
Sample https://travis-ci.org/nschonni/digital-playbook-guide-numerique/builds/362348596

### CODE REVIEW

**Comment by nschonni** [comment]
Silenced the existing failures so this can be enabled and fixed up afterwards https://travis-ci.org/nschonni/digital-playbook-guide-numerique/builds/364233710

**Comment by pjackson28** [comment]
@nschonni Thanks for this.

**Comment by pjackson28** [comment]
@nschonni Do you have a list of existing failures (when the checks are turned on) that could be submitted as an issue so they can be addressed? Welcome your help on cleaning up the failures if you have time.

**Comment by nschonni** [comment]
The travis build link in the issue should have all of them, since I hadn't disabled anything (except the line length rule) at that time.
I can spin up individual issues for re-enabling all the rules I `TODO'd` if you want

**Comment by pjackson28** [comment]
I looked in the linked Travis build but didn't see any failures (even when I expanded the build information section). I'm flexible as to where to share the issues, whether it be in a Travis build or somewhere else.

**Pull request merged**
