### PR TITLE
chore: Add link checking

### LINKED ISSUE #31: Add link checking functionality

### PR DESCRIPTION
**Pull request by nschonni**
Still seems kind of hacky since I needed to do a custom wrapper in order to skip the problem of GCPedia and the Industry Canada wiki not being available outside of the GC network.

It did manage to pick up a dead link (French and English)
Reading: fr/1-concevoir-avec-utilisateurs.md
Dead: https://www.tbs-sct.gc.ca/pol/doc-fra.aspx?id=27916b#cha7

Reading: en/1-design-with-users.md
Dead: https://www.tbs-sct.gc.ca/pol/doc-eng.aspx?id=27916b#cha7

Closes #31

### CODE REVIEW

**Comment by pjackson28** [comment]
Looks like the link is broken because of the "b" before the "#". Once that is removed, the link works.

**Comment by pjackson28** [comment]
Fixed the broken links in PR #63

**Comment by nschonni** [comment]
Rebased. From inside the GOC network it was still flagging these for me
- http://www.gcpedia.gc.ca/wiki/Sprint_(CRA_Agile_Framework)
  - Think this is just it getting confused with the trailing brace, but it still won't fail the build
- http://wiki.ic.gc.ca/pages/viewpage.action?pageId=566756956
  - Think this may just be only available on the IC network

**Comment by pjackson28** [comment]
The wiki.ic.gc.ca link should be removed if we can't access it. Where in the playbook did you find it?

**Pull request merged**
