### PR TITLE
Update to 9 - Address security and privacy

### PR DESCRIPTION
**Pull request by tallardyce**
Updates made to the initial security and privacy content, matching the content provided to Paul Jackson, with recommended edits.

### CODE REVIEW

**Comment by pjackson28** [comment]
I resolved the merge conflicts and MarkdownLint errors for you. Please review the content just to be sure I didn't change something I shouldn't have while resolving the merge conflicts.

**Comment by tallardyce** [comment]
Content looks fine by me, Paul - thanks!

**Comment by pjackson28** [comment]
@tallardyce Are we waiting on any more content reviews or should I go ahead with merging in this content?

**Comment by tallardyce** [comment]
Closing the pull request as there's a new one based on the edits from Po to review/approve and merge.

**Comment by pjackson28** [comment]
@tallardyce No problem with closing this pull request. You also had the option of making the changes in the branch where you did the pull request. Any changes to that branch would have automatically updated this pull request. Doesn't make much of a difference in the end but it could reduce your amount of effort a bit.

**Pull request closed without merging**
